### ISSUE TITLE
Not able to build train-kubernetes

### ISSUE THREAD

**Issue by ankurpshah** [bgeesaman/train-kubernetes#1]
I tried a lot to build train-kubernetes. It is not working for me. If possible then can you provide a containerized setup of train-kubernetes? I am a big fan of Inspec and kitchen and eagerly waiting for Inspec-kitchen-kubernetes integration.

**Comment by bgeesaman** [comment]
Spent a good chunk today refreshing this gem for Inspec 4.x, validating dependencies, and tweaking the instructions.  Please take a look at https://github.com/bgeesaman/inspec-k8s-sample for a dockerized profile example and let me know how it goes!
